export const HOME_GET_FILM_MOVIE = "HOME_GET_FILM_MOVIE"
export const HOME_GET_FILM_MOVIE_SUCCESS = "HOME_GET_FILM_MOVIE_SUCCESS"

export const HOME_GET_FILM_MOVIE_FAIL = "HOME_GET_FILM_MOVIE_FAIL"
export const HOME_GET_FILM_TV = "HOME_GET_FILM_TV"
export const HOME_GET_FILM_TV_SUCCESS = "HOME_GET_FILM_TV_SUCCESS"

export const HOME_GET_GENRES_MOVIE = "HOME_GET_GENRES_MOVIE"
export const HOME_GET_GENRES_MOVIE_SUCCESS = "HOME_GET_GENRES_MOVIE_SUCCES"
export const HOME_GET_GENRES_MOVIE_FAIL = "HOME_GET_GENRES_MOVIE_FAIL"

export const HOME_GET_GENRES_TV = "HOME_GET_GENRES_TV"
export const HOME_GET_GENRES_TV_SUCCESS = "HOME_GET_GENRES_TV_SUCCESS"
export const HOME_GET_GENRES_TV_FAIL = "HOME_GET_GENRES_TV_FAIL"

export const HOME_GET_FILM_BY_GENRE_MOVIE = "HOME_GET_FILM_BY_GENRE_MOVIE"
export const HOME_GET_FILM_BY_GENRE_MOVIE_SUCCESS = "HOME_GET_FILM_BY_GENRE_MOVIE_SUCCESS"

export const HOME_GET_MOVIE_DETAIL = "HOME_GET_MOVIE_DETAIL"
export const HOME_GET_MOVIE_DETAIL_SUCCESS = "HOME_GET_MOVIE_DETAIL_SUCCESS"
export const HOME_GET_MOVIE_DETAIL_FAIL = "HOME_GET_MOVIE_DETAIL_FAIL"

export const HOME_GET_TV_DETAIL = "HOME_GET_TV_DETAIL"
export const HOME_GET_TV_DETAIL_SUCCESS = "HOME_GET_TV_DETAIL_SUCCESS"
export const HOME_GET_TV_DETAIL_FAIL = "HOME_GET_TV_DETAIL_FAIL"

export const HOME_GET_ACTOR = "HOME_GET_ACTOR"
export const HOME_GET_ACTOR_SUCCESS = "HOME_GET_ACTOR_SUCCESS"
export const HOME_GET_ACTOR_FAIL = "HOME_GET_ACTOR_FAIL"

export const HOME_GET_TRAILER = "HOME_GET_TRAILER"
export const HOME_GET_TRAILER_SUCCESS = "HOME_GET_TRAILER_SUCCESS"
export const HOME_GET_TRAILER_FAIL = "HOME_GET_TRAILER_FAIL"

export const SHOW_LOADING = "SHOW_LOADING"
export const HIDE_LOADING = "HIDE_LOADING"

export const HOME_GET_RECOMMEND_FILM = "HOME_GET_RECOMMEND_FILM"
export const HOME_GET_RECOMMEND_FILM_SUCCESS = "HOME_GET_RECOMMEND_FILM_SUCCESS"
export const HOME_GET_RECOMMEND_FILM_FAIL = "HOME_GET_RECOMMEND_FILM_FAIL"